var Util={uuid:function(){var a,f,d=[];for(f=0;36>f;f+=1)d[f]=(16*Math.random()|0).toString(16);d[8]=d[13]=d[18]=d[23]="-";d[14]="4";d[19]="89ab".charAt(4*Math.random()|0);a=d.join("");return{toString:function(){return a},valueOf:function(){return a}}},isIOS6:function(){return/(iPhone|iPod|iPad)/i.test(navigator.userAgent)&&/OS [6](.*) like Mac OS X/i.test(navigator.userAgent)?!0:!1},isOpera:function(){return window.opera||jQuery.browser.opera},isIE:function(){return jQuery.browser.msie},isChrome:function(){return"object"===
typeof window.chrome||/chrome/.test(navigator.userAgent.toLowerCase())||/chrom(e|ium)/.test(navigator.userAgent.toLowerCase())},closeDDLevelsMenu:function(a,f){var d=!0,e=ddlevelsmenu.topitems.nav;if(e)for(var c=0;c<e.length;c++)0<jQuery(e[c].parentNode).has(f).length&&(d=!1);if(d&&(e=ddlevelsmenu.subuls.nav))for(c=0;c<e.length;c++)0<jQuery(e[c]).has(f).length&&(d=!1);if(d&&(e=ddlevelsmenu.subuls.nav))for(c=0;c<e.length;c++)ddlevelsmenu.hidemenu(e[c].parentNode)}};
(function(a){a.fn.flexSliderInitializer=function(f){function d(c){c=a(c);g=c.find("iframe");var d=a.extend({},{smoothHeight:"slide"==e,pauseOnHover:!0,video:"slide"==e,before:function(){0<g.length&&window.$f&&g.each(function(){try{$f(this).api("pause")}catch(a){}})}},f);console.log(d);c.fitVids().flexslider(d);if(Modernizr.touch&&a().swipe){var k=c.find("a.flex-next"),b=c.find("a.flex-prev"),d=function(a,c){"left"==c.toLowerCase()&&k.trigger("click");"right"==c.toLowerCase()&&b.trigger("click")};
c.swipe({click:function(c,b){a(b).trigger("click")},swipeLeft:d,swipeRight:d,allowPageScroll:"auto"})}}var e=f.animation,c=a(f.controlsContainer),g;0<c.length&&c.each(function(){var c=this,e=!1,f=0,b=[];a(c).find("img").each(function(){!this.complete&&void 0!=this.complete&&(b.push(this),f++)});if(0==f)d(c);else{var p=0;a(b).bind("load",function(){p++;p===f&&!e&&(e=!0,d(c))});var q=window.setTimeout(function(){window.clearTimeout(q);a(b).each(function(){(this.complete||void 0===this.complete)&&a(this).trigger("load")})},
50)}})}})(jQuery);(function(a){a.fn.responsiveSearch=function(f){function d(a){a?g.fadeIn(c.animSpeed):g.fadeOut(c.animSpeed)}var e=a.fn.responsiveSearch,c=a.extend({},e.defaults,f),g=a(this);a("#search-submit").bind("click",function(){return"none"==g.css("display")?(d(!0),!1):""==a.trim(g.val())?(d(!1),!1):!0});e.hide=function(a){"s"!=a.id&&"search-submit"!=a.id&&"none"!=g.css("display")&&d(!1)};return e};a.fn.responsiveSearch.defaults={animSpeed:500}})(jQuery);
Util.isIOS6()&&function(a){function f(c,b,d){var e,f=d[0],h=c===n;d[0]=function(){f&&(f.apply(a,arguments),h||(delete b[e],f=null))};e=c.apply(a,d);b[e]={args:d,created:Date.now(),cb:f,id:e};return e}function d(c,b,d,e){function f(){h.cb&&(h.cb.apply(a,arguments),g||(delete d[e],h.cb=null))}var h=d[e];if(h){var g=c===n;b(h.id);if(!g){b=h.args[1];var k=Date.now()-h.created;0>k&&(k=0);b-=k;0>b&&(b=0);h.args[1]=b}h.args[0]=f;h.created=Date.now();h.id=c.apply(a,h.args)}}var e={},c={},g=a.setTimeout,n=
a.setInterval,u=a.clearTimeout,k=a.clearInterval;if(!a.addEventListener)return!1;a.setTimeout=function(){return f(g,e,arguments)};a.setInterval=function(){return f(n,c,arguments)};a.clearTimeout=function(a){var c=e[a];c&&(delete e[a],u(c.id))};a.clearInterval=function(a){var b=c[a];b&&(delete c[a],k(b.id))};for(var b=a;b.location!=b.parent.location;)b=b.parent;b.addEventListener("scroll",function(){for(var a in e)d(g,u,e,a);for(a in c)d(n,k,c,a)})}(window);
jQuery(document).ready(function(a){function f(a){a.data("resizing")&&a.css("left","0")}function d(){var j=a(window).width();return 480>j?1:768>j?2:960>j?3:4}function e(j,c){var l=a(j.currentTarget).parents().eq(2);"left"==c.toLowerCase()&&l.find(".jcarousel-next").trigger("click");"right"==c.toLowerCase()&&l.find(".jcarousel-prev").trigger("click")}function c(j,c){var l=j.customSettings,b=a(j.selector);0<b.length&&(b.each(function(){var j=a(this),c=a.extend({},{scroll:1,visible:1,wrap:"last",easing:"swing",
itemVisibleInCallback:function(){f(j);f(j)}},l);c.scroll=Math.min(d(),c.scroll);j.jcarousel(c)}),c&&(Modernizr.touch&&a().swipe)&&b.swipe({click:function(j,c){a(c).trigger("click")},swipeLeft:e,swipeRight:e,allowPageScroll:"auto"}))}function g(j){var b=a(j.selector);0<b.length&&b.each(function(){var b=a(this),d=b.children("li"),e=d.first().outerWidth(!0),d=d.length*e+100;if(b.width()!==d){b.css("width",d).data("resizing","true");c(j,!1);b.jcarousel("scroll",1);var C=window.setTimeout(function(){window.clearTimeout(C);
b.data("resizing",null)},600)}})}function n(){if(0<m.length){var a=m.width(),a=Math.round(0.425*a);m.height(a)}}function u(){var c=a("body"),b=a("#wrap"),l=a("#content");l.css("min-height",a(window).outerHeight(!0)-(c.outerHeight(!0)-c.height())-(b.outerHeight(!0)-b.height())-a("#header").outerHeight(!0)-a("#slider-home").outerHeight(!0)-a("#page-title").outerHeight(!0)-(l.outerHeight(!0)-l.height())-a("#footer").outerHeight(!0))}Util.isOpera()&&a(".flexslider .slides > li").each(function(){a(this).css("overflow",
"hidden")});var k=[{selector:".post-carousel",customSettings:{}},{selector:".testimonial-carousel",customSettings:{auto:5}},{selector:".project-carousel",customSettings:{scroll:4,visible:null}}];if(a().jcarousel&&k)for(var b=0;b<k.length;b++)c(k[b],!0);a().tinyNav&&(a("html").addClass("js"),a("#navlist").tinyNav());b=a("#s");if(0<b.length)var p=b.responsiveSearch();a().fitVids&&a(".entry-video").fitVids();b=[{controlsContainer:"#flexslider-home",animation:"fade",slideshow:!0,slideshowSpeed:7E3,animationSpeed:600},
{controlsContainer:"#flexslider-about-us",animation:"slide",slideshow:!1,slideshowSpeed:7E3,animationSpeed:600},{controlsContainer:"#flexslider-portfolio-item",animation:"slide",slideshow:!1,slideshowSpeed:7E3,animationSpeed:600}];if(a().flexslider&&b)for(var q=0;q<b.length;q++)a().flexSliderInitializer(b[q]);if(a().revolution){var r=jQuery;r.noConflict();r(document).ready(function(){void 0!=r.fn.cssOriginal&&(r.fn.css=r.fn.cssOriginal);r(".fullwidthbanner").revolution({delay:9E3,startwidth:940,startheight:400,
onHoverStop:"on",thumbWidth:100,thumbHeight:50,thumbAmount:3,hideThumbs:200,navigationType:"bullet",navigationArrows:"verticalcentered",navigationStyle:"round",touchenabled:"on",navOffsetHorizontal:0,navOffsetVertical:20,stopAtSlide:-1,stopAfterLoops:-1,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,hideSliderAtLimit:0,fullWidth:"on",shadow:0})})}if(a().fancybox){var v=function(c,b){var l=a("#fancybox-buttons"),d=l.find(".btnNext"),l=l.find(".btnPrev");"left"==b.toLowerCase()&&d&&d.trigger("click");
"right"==b.toLowerCase()&&l&&l.trigger("click")},z=function(b,c){var d=a(window).width();return d<1.3*b?(d*=0.75,{width:d,height:d*c/b}):!1};a(".lightbox-video").each(function(){var b=a(this),c=b.data("width")?b.data("width"):800,d=b.data("height")?b.data("height"):450;b.fancybox({autoScale:!1,transitionIn:"none",transitionOut:"none",title:this.title,width:c,height:d,type:"iframe",fitToView:!1,openEffect:"fade",closeEffect:"fade",nextEffect:"fade",prevEffect:"fade",arrows:!Modernizr.touch,helpers:{title:{type:"inside"},
buttons:{},media:{}},beforeShow:function(){var a=z(c,d);a&&(this.width=a.width,this.height=a.height)},onUpdate:function(){var a=z(c,d);a&&(this.width=a.width,this.height=a.height)},beforeLoad:function(){this.title="Image "+(this.index+1)+" of "+this.group.length+(this.title?" - "+this.title:"")},afterShow:function(){if(Modernizr.touch&&a().swipe){var b=a(".fancybox-wrap");"true"!==b.data("swipe")&&(b.data("swipe","true"),b.swipe({click:function(b,c){a(c).trigger("click")},swipeLeft:v,swipeRight:v,
allowPageScroll:"auto"}))}}})});var h=[];a(".lightbox").each(function(){var b=a(this).parent(),c=!0;b&&b.hasClass("clone")&&(c=!1);c&&h.push(this)});a(h).fancybox({openEffect:"fade",closeEffect:"fade",nextEffect:"fade",prevEffect:"fade",arrows:!Modernizr.touch,helpers:{title:{type:"inside"},buttons:{},media:{}},beforeLoad:function(){this.title="Image "+(this.index+1)+" of "+this.group.length+(this.title?" - "+this.title:"")},afterShow:function(){if(Modernizr.touch&&a().swipe){var b=a(".fancybox-wrap");
"true"!==b.data("swipe")&&(b.data("swipe","true"),b.swipe({click:function(b,c){a(c).trigger("click")},swipeLeft:v,swipeRight:v,allowPageScroll:"auto"}))}}})}a().tipsy&&a(".clients img[title], .social-links a[title], .entry-slider img[title]").tipsy({fade:!0,gravity:a.fn.tipsy.autoNS,offset:3});a().UItoTop&&a().UItoTop({scrollSpeed:400});a("iframe").each(function(){var b=a(this).attr("src");if(-1!=b.indexOf("?")){var c=b.split("?"),b=c[1],c=c[0];a(this).attr("src",c+"?wmode=transparent&"+b)}else a(this).attr("src",
b+"?wmode=transparent")});a(".notification-close-info").click(function(){a(".notification-box-info").fadeOut("fast");return!1});a(".notification-close-success").click(function(){a(".notification-box-success").fadeOut("fast");return!1});a(".notification-close-warning").click(function(){a(".notification-box-warning").fadeOut("fast");return!1});a(".notification-close-error").click(function(){a(".notification-box-error").fadeOut("fast");return!1});a().tabs&&a(".tabs").tabs();a().toggle&&a(".toggle").each(function(){"open"==
a(this).attr("data-id")?a(this).accordion({header:".toggle-title",collapsible:!0,heightStyle:"content"}):a(this).accordion({header:".toggle-title",collapsible:!0,heightStyle:"content",active:!1})});a().accordion&&a(".accordion").accordion({header:".accordion-title",collapsible:!0,heightStyle:"content"});var A=a("#gallery");a.isotope&&A.isotope({itemSelector:".entry"});a("#filter").find("a").click(function(){var b=a(this).attr("data-filter");A.isotope({filter:b});return!1});a(".option-set").find("a").click(function(){var b=
a(this);if(b.hasClass("selected"))return!1;b.parents(".option-set").find(".selected").removeClass("selected");b.addClass("selected")});a().validate&&a("#comment-form").validate();var s=a("#contact-form");if(s&&0<s.length){var w=s.find("#submit");w.bind("click",function(b){function c(){var d="timestamp="+b.timeStamp;s.find(":input").each(function(){var b=a(this),c=!0;b.is(":checkbox")&&!b.is(":checked")&&(c=!1);c&&(c=b.attr("name"),b=a.trim(b.val()),0<b.length&&(d+="&"+c+"="+b))});return d}s.valid()&&
(w.attr("disabled","disabled"),a.ajax({type:"POST",url:"contact-processor.php",data:c(),statusCode:{200:function(){a("#contact-notification-box-success").css("display","");w.removeAttr("disabled","");s.find(":input").each(function(){var b=a(this);if("select"==b.prop("nodeName").toLowerCase())b.prop("selectedIndex",0);else if(b.is(":checkbox"))b.attr("checked",b.prop("defaultChecked"));else{var c=b.prop("defaultValue");c?b.val(c):b.val("")}})},500:function(b){var c=a("#contact-notification-box-error-msg");
b=b.responseText;if(!b||0==b.length)b=c.data("default-msg");c.text(b);a("#contact-notification-box-error").css("display","");w.removeAttr("disabled")}}}));return!1})}a().validate&&a("#send-newsletter-form").validate();if((b=a("#newsletter-form"))&&0<b.length){var y=b.find("#subscribe"),t=b.find("#newsletter");y.bind("click",function(){function b(){var a="action=subscribe";t&&0<t.length&&(a+="&email="+t.attr("value"));return a}a("#newsletter-form").valid()&&(a("#subscribe").attr("disabled","disabled"),
jQuery.ajax({type:"POST",url:"newsletter.php",data:b(),statusCode:{200:function(){a("#newsletter-notification-box-success").css("display","");y.removeAttr("disabled","");t&&0<t.length&&t.attr("value","")},500:function(){a("#newsletter-notification-box-error").css("display","");y.removeAttr("disabled")}}}));return!1})}a().tweet&&a(".tweet").tweet({username:"ixtendo",join_text:!1,avatar_size:!1,count:2,view_text:"view tweet on twitter",seconds_ago_text:"about %d seconds ago",a_minutes_ago_text:"about a minute ago",
minutes_ago_text:"about %d minutes ago",a_hours_ago_text:"about an hour ago",hours_ago_text:"about %d hours ago",a_day_ago_text:"about a day ago",days_ago_text:"about %d days ago",template:"{avatar}{text}{join}{time}"});a().jflickrfeed&&a(".flickr-feed").jflickrfeed({limit:6,qstrings:{id:"52617155@N08"},itemTemplate:'<li><a href="{{link}}" title="{{title}}" target="_blank"><img src="{{image_s}}" alt="{{title}}" /></a></li>'});var m=a("#map");if(a().gMap&&0<m.length){var b=m.data("lat"),q=m.data("lng"),
B=m.data("address"),D=m.data("zoom"),x={};B?x.address=B:(x.latitude=b,x.longitude=q);m.gMap({markers:[x],zoom:D})}n();u();a(window).on("resize",function(){var b=window.setTimeout(function(){window.clearTimeout(b);u();if(a().jcarousel&&k)for(var c=0;c<k.length;c++)g(k[c]);n()},30)});if(Modernizr.touch)a(document).on("touchstart",function(a){var b=a.target;p&&p.hide(b);Util.closeDDLevelsMenu(a,b)});else a(document).click(function(a){Util.closeDDLevelsMenu(a,"");p&&p.hide(a.target)});480<a(window).width()&&
(b=0>window.location.href.indexOf("#nosw"),a().styleSwitcher&&b&&(b=a().styleSwitcher(),b.loadStyleSwitcher(),b.applySettings()))});